package service

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/multica-ai/multica/server/internal/testutil"
	"github.com/multica-ai/multica/server/internal/util"
	db "github.com/multica-ai/multica/server/pkg/db/generated"
)

// Graph rows are an additive queue kind (migration 602): graph_run_id,
// work_source_id, work_native_id set, no issue/chat/autopilot/wakeup identity.
// Legacy queue mutators in pkg/db/queries/agent.sql, runtime.sql and
// supplement.sql carry graph_run_id IS NULL guards. CountRunningTasks instead
// includes execution_uncertain graph reservations. This bounded workflow matrix
// exercises generated queries against real SQL, comparing whole graph rows and
// checking matched legacy behavior. It does not test every guarded query.
//
// The queries are regenerated by root after this source is stable, so the
// cases referencing generated symbols compile only after `make sqlc`.

type graphFenceFixture struct {
	pool        *pgxpool.Pool
	dbfx        *testutil.Fixture
	q           *db.Queries
	workspaceID string
	userID      string
	runtimeID   string
	agentID     string
	sourceID    pgtype.UUID
	runID       pgtype.UUID
}

func newGraphFenceFixture(t *testing.T) *graphFenceFixture {
	t.Helper()
	pool := newResolveOriginatorPool(t)
	dbfx := testutil.New(pool, "", "")
	suffix := time.Now().UnixNano()
	f := &graphFenceFixture{pool: pool, dbfx: dbfx}
	f.workspaceID = dbfx.Workspace(t, "Graph Fence", fmt.Sprintf("graph-fence-%d", suffix))
	f.userID = dbfx.User(t, "Graph Fence Owner", fmt.Sprintf("graph-fence-owner-%d@multica.test", suffix))
	dbfx.WorkspaceID, dbfx.UserID = f.workspaceID, f.userID
	dbfx.Member(t, f.workspaceID, f.userID, "owner")
	f.runtimeID = dbfx.Runtime(t, "graph-fence-runtime", testutil.Cols{
		"workspace_id": f.workspaceID,
		"status":       "online",
		"last_seen_at": time.Now(),
	})
	f.agentID = dbfx.Agent(t, "graph-fence-agent", f.runtimeID, testutil.Cols{
		"workspace_id": f.workspaceID,
		"owner_id":     f.userID,
	})
	// Queue graph identity has no FKs by design: fresh random UUIDs satisfy
	// agent_task_graph_identity_check without any work_source/workflow_run rows
	// (same pattern as the task_graph_slot suite).
	f.sourceID = util.MustParseUUID(uuid.NewString())
	f.runID = util.MustParseUUID(uuid.NewString())
	f.q = db.New(pool)
	return f
}

func graphText(s string) pgtype.Text { return pgtype.Text{String: s, Valid: true} }

// seedGraphTask inserts a queued-by-default graph attempt. Graph rows carry no
// issue/chat/autopilot identity (agent_task_graph_identity_check).
func (f *graphFenceFixture) seedGraphTask(t *testing.T, status string, over ...testutil.Cols) pgtype.UUID {
	t.Helper()
	return util.MustParseUUID(f.dbfx.Task(t, f.agentID, append([]testutil.Cols{{
		"runtime_id":          f.runtimeID,
		"status":              status,
		"graph_run_id":        util.UUIDToString(f.runID),
		"work_source_id":      util.UUIDToString(f.sourceID),
		"work_native_id":      fmt.Sprintf("native-%d", time.Now().UnixNano()),
		"execution_uncertain": false,
	}}, over...)...))
}

// seedLegacyTask inserts a matched legacy row that the mutator must still reach.
func (f *graphFenceFixture) seedLegacyTask(t *testing.T, status string, over ...testutil.Cols) pgtype.UUID {
	t.Helper()
	return util.MustParseUUID(f.dbfx.Task(t, f.agentID, append([]testutil.Cols{{
		"runtime_id": f.runtimeID,
		"status":     status,
		"priority":   1,
	}}, over...)...))
}

type graphTaskState struct {
	Status             string
	ExecutionUncertain bool
	RuntimeID          *string
	IssueID            *string
	SessionID          *string
}

func (f *graphFenceFixture) taskState(t *testing.T, id pgtype.UUID) graphTaskState {
	t.Helper()
	var s graphTaskState
	if err := f.pool.QueryRow(context.Background(), `
		SELECT status, execution_uncertain, runtime_id::text, issue_id::text, session_id
		FROM agent_task_queue WHERE id = $1`, id).
		Scan(&s.Status, &s.ExecutionUncertain, &s.RuntimeID, &s.IssueID, &s.SessionID); err != nil {
		t.Fatalf("load task state: %v", err)
	}
	return s
}

// taskJSON returns the whole row as one comparable string: every column the
// guarded mutators could touch (status, timestamps, context, retry lineage,
// dispatch settings, control state, graph identity) is covered by equality.
func (f *graphFenceFixture) taskJSON(t *testing.T, id pgtype.UUID) string {
	t.Helper()
	var s string
	if err := f.pool.QueryRow(context.Background(), `SELECT to_jsonb(atq)::text FROM agent_task_queue atq WHERE atq.id = $1`, id).Scan(&s); err != nil {
		t.Fatalf("load task row json: %v", err)
	}
	return s
}

func TestGraphTaskLegacyFenceMatrix(t *testing.T) {
	leaseSecs := float64(60)
	staleSecs := float64(3600)
	graceSecs := float64(0)
	maxPerTick := int32(100)
	timeoutSecs := float64(0)
	fenceRunUUID := pgtype.UUID{Bytes: [16]byte{0xaa}, Valid: true}
	ctx := context.Background()

	cases := []struct {
		name  string
		setup func(t *testing.T, f *graphFenceFixture) (graphID, legacyID pgtype.UUID)
		run   func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID)
		// legacyAssert is the REQUIRED positive control: the matched legacy row
		// must have been mutated in the specific way this query exists to do.
		legacyAssert func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID)
	}{
		{
			name: "ClaimAgentTask skips graph candidate and claims legacy",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "queued", testutil.Cols{"priority": 9, "created_at": time.Now().Add(-time.Hour)})
				legacyID := f.seedLegacyTask(t, "queued")
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				claimed, err := f.q.ClaimAgentTask(ctx, db.ClaimAgentTaskParams{
					PrepareLeaseSecs: leaseSecs,
					AgentID:          util.MustParseUUID(f.agentID),
					RuntimeID:        util.MustParseUUID(f.runtimeID),
					RuntimeStaleSecs: staleSecs,
				})
				if err != nil {
					t.Fatalf("ClaimAgentTask: %v", err)
				}
				if claimed.ID != legacyID {
					t.Fatalf("ClaimAgentTask claimed %s, want legacy %s", claimed.ID, legacyID)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "dispatched" {
					t.Fatalf("legacy claim status = %q, want dispatched", s.Status)
				}
			},
		},
		{
			name: "RequeueAgentTaskAfterClaimFailure leaves graph dispatch generation intact",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "dispatched", testutil.Cols{"dispatched_at": time.Now()})
				legacyID := f.seedLegacyTask(t, "dispatched", testutil.Cols{"dispatched_at": time.Now()})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				dispatchedAtFor := func(id pgtype.UUID) time.Time {
					var at time.Time
					if err := f.pool.QueryRow(ctx, `SELECT dispatched_at FROM agent_task_queue WHERE id = $1`, id).Scan(&at); err != nil {
						t.Fatalf("read dispatched_at: %v", err)
					}
					return at
				}
				if _, err := f.q.RequeueAgentTaskAfterClaimFailure(ctx, db.RequeueAgentTaskAfterClaimFailureParams{
					TaskID:       graphID,
					RuntimeID:    util.MustParseUUID(f.runtimeID),
					DispatchedAt: pgtype.Timestamptz{Time: dispatchedAtFor(graphID), Valid: true},
				}); err == nil {
					t.Fatal("RequeueAgentTaskAfterClaimFailure mutated a graph row")
				}
				if _, err := f.q.RequeueAgentTaskAfterClaimFailure(ctx, db.RequeueAgentTaskAfterClaimFailureParams{
					TaskID:       legacyID,
					RuntimeID:    util.MustParseUUID(f.runtimeID),
					DispatchedAt: pgtype.Timestamptz{Time: dispatchedAtFor(legacyID), Valid: true},
				}); err != nil {
					t.Fatalf("legacy requeue: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "queued" {
					t.Fatalf("legacy requeue status = %q, want queued", s.Status)
				}
			},
		},
		{
			name: "ExtendAgentTaskPrepareLease skips graph row",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "dispatched")
				legacyID := f.seedLegacyTask(t, "dispatched")
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				p := db.ExtendAgentTaskPrepareLeaseParams{RuntimeID: util.MustParseUUID(f.runtimeID), LeaseSecs: leaseSecs}
				p.ID = graphID
				if _, err := f.q.ExtendAgentTaskPrepareLease(ctx, p); err == nil {
					t.Fatal("ExtendAgentTaskPrepareLease mutated a graph row")
				}
				p.ID = legacyID
				if _, err := f.q.ExtendAgentTaskPrepareLease(ctx, p); err != nil {
					t.Fatalf("legacy lease extend: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				var lease time.Time
				if err := f.pool.QueryRow(context.Background(), `SELECT prepare_lease_expires_at FROM agent_task_queue WHERE id = $1`, legacyID).Scan(&lease); err != nil {
					t.Fatalf("read legacy lease: %v", err)
				}
				if lease.Before(time.Now()) {
					t.Fatalf("legacy lease not extended: %v", lease)
				}
			},
		},
		{
			name: "StartAgentTask family rejects graph rows",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "dispatched", testutil.Cols{"dispatched_at": time.Now()})
				legacyID := f.seedLegacyTask(t, "dispatched", testutil.Cols{"dispatched_at": time.Now()})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				if _, err := f.q.StartAgentTask(ctx, graphID); err == nil {
					t.Fatal("StartAgentTask mutated a graph row")
				}
				if _, err := f.q.StartAgentTaskWithRun(ctx, db.StartAgentTaskWithRunParams{ID: graphID, ActiveRunID: fenceRunUUID}); err == nil {
					t.Fatal("StartAgentTaskWithRun mutated a graph row")
				}
				if _, err := f.q.StartAgentTaskWithSupplement(ctx, db.StartAgentTaskWithSupplementParams{TaskID: graphID}); err == nil {
					t.Fatal("StartAgentTaskWithSupplement mutated a graph row")
				}
				var dispatchedAt time.Time
				if err := f.pool.QueryRow(ctx, `SELECT dispatched_at FROM agent_task_queue WHERE id = $1`, graphID).Scan(&dispatchedAt); err != nil {
					t.Fatalf("read graph dispatched_at: %v", err)
				}
				if _, err := f.q.LockAgentTaskStartClaim(ctx, db.LockAgentTaskStartClaimParams{
					ID: graphID, RuntimeID: util.MustParseUUID(f.runtimeID), DispatchedAt: pgtype.Timestamptz{Time: dispatchedAt, Valid: true},
				}); err == nil {
					t.Fatal("LockAgentTaskStartClaim locked a graph row")
				}
				if _, err := f.q.StartAgentTask(ctx, legacyID); err != nil {
					t.Fatalf("legacy start: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "running" {
					t.Fatalf("legacy start status = %q, want running", s.Status)
				}
			},
		},
		{
			name: "MarkAgentTaskWaitingLocalDirectory skips graph row",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "dispatched")
				legacyID := f.seedLegacyTask(t, "dispatched")
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				p := db.MarkAgentTaskWaitingLocalDirectoryParams{WaitReason: graphText("/tmp"), PrepareLeaseSecs: leaseSecs}
				p.ID = graphID
				if _, err := f.q.MarkAgentTaskWaitingLocalDirectory(ctx, p); err == nil {
					t.Fatal("MarkAgentTaskWaitingLocalDirectory mutated a graph row")
				}
				p.ID = legacyID
				if _, err := f.q.MarkAgentTaskWaitingLocalDirectory(ctx, p); err != nil {
					t.Fatalf("legacy wait transition: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "waiting_local_directory" {
					t.Fatalf("legacy wait status = %q, want waiting_local_directory", s.Status)
				}
			},
		},
		{
			name: "CompleteAgentTask and FailAgentTask reject graph rows",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "running", testutil.Cols{"started_at": time.Now()})
				legacyID := f.seedLegacyTask(t, "running", testutil.Cols{"started_at": time.Now()})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				if _, err := f.q.CompleteAgentTask(ctx, db.CompleteAgentTaskParams{ID: graphID, Result: []byte("{}"), SessionRolloutMissing: true}); err == nil {
					t.Fatal("CompleteAgentTask mutated a graph row")
				}
				if _, err := f.q.FailAgentTask(ctx, db.FailAgentTaskParams{ID: graphID, Error: graphText("boom"), SessionRolloutMissing: true}); err == nil {
					t.Fatal("FailAgentTask mutated a graph row")
				}
				if _, err := f.q.CompleteAgentTask(ctx, db.CompleteAgentTaskParams{ID: legacyID, Result: []byte("{}"), SessionRolloutMissing: true}); err != nil {
					t.Fatalf("legacy complete: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "completed" {
					t.Fatalf("legacy complete status = %q, want completed", s.Status)
				}
			},
		},
		{
			name: "CancelAgentTask family and CancelAgentTasksByAgent leave graph rows alone",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "running")
				legacyID := f.seedLegacyTask(t, "running")
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				if _, err := f.q.CancelAgentTask(ctx, graphID); err == nil {
					t.Fatal("CancelAgentTask mutated a graph row")
				}
				if _, err := f.q.CancelAgentTaskWithReason(ctx, db.CancelAgentTaskWithReasonParams{ID: graphID, Error: graphText("no"), FailureReason: graphText("refused")}); err == nil {
					t.Fatal("CancelAgentTaskWithReason mutated a graph row")
				}
				cancelled, err := f.q.CancelAgentTasksByAgent(ctx, util.MustParseUUID(f.agentID))
				if err != nil {
					t.Fatalf("CancelAgentTasksByAgent: %v", err)
				}
				if len(cancelled) != 1 || cancelled[0].ID != legacyID {
					t.Fatalf("CancelAgentTasksByAgent = %d rows, want exactly the legacy row", len(cancelled))
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "cancelled" {
					t.Fatalf("legacy cancel status = %q, want cancelled", s.Status)
				}
			},
		},
		{
			name: "UpdateAgentTaskSession does not pin graph rows",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "running")
				legacyID := f.seedLegacyTask(t, "running")
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				p := db.UpdateAgentTaskSessionParams{SessionID: graphText("session-1"), WorkDir: graphText("/w")}
				p.ID = graphID
				if err := f.q.UpdateAgentTaskSession(ctx, p); err != nil {
					t.Fatalf("UpdateAgentTaskSession: %v", err)
				}
				if s := f.taskState(t, graphID); s.SessionID != nil {
					t.Fatalf("UpdateAgentTaskSession pinned a graph row: %+v", s)
				}
				p.ID = legacyID
				if err := f.q.UpdateAgentTaskSession(ctx, p); err != nil {
					t.Fatalf("legacy session pin: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.SessionID == nil || *s.SessionID != "session-1" {
					t.Fatalf("legacy session pin = %v, want session-1", s.SessionID)
				}
			},
		},
		{
			name: "RecoverOrphanedTasksForRuntime recovers legacy rows only",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "running", testutil.Cols{"started_at": time.Now()})
				legacyID := f.seedLegacyTask(t, "running", testutil.Cols{"started_at": time.Now()})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				recovered, err := f.q.RecoverOrphanedTasksForRuntime(ctx, util.MustParseUUID(f.runtimeID))
				if err != nil {
					t.Fatalf("RecoverOrphanedTasksForRuntime: %v", err)
				}
				if len(recovered) != 1 || recovered[0].ID != legacyID {
					t.Fatalf("recovered %d rows, want exactly the legacy row", len(recovered))
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "failed" {
					t.Fatalf("legacy recover status = %q, want failed", s.Status)
				}
			},
		},
		{
			name: "FailStaleTasks, ExpireStaleQueuedTasks and FailTasksForOfflineRuntimes skip graph rows",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "running", testutil.Cols{
					"started_at":    time.Now().Add(-24 * time.Hour),
					"dispatched_at": time.Now().Add(-24 * time.Hour),
				})
				legacyID := f.seedLegacyTask(t, "running", testutil.Cols{"started_at": time.Now().Add(-24 * time.Hour), "dispatched_at": time.Now().Add(-24 * time.Hour)})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				// A dead runtime so the sweepers genuinely target the legacy row.
				if _, err := f.pool.Exec(ctx, `
					UPDATE agent_runtime SET status = 'offline', last_seen_at = now() - interval '24 hours'
					WHERE id = $1`, f.runtimeID); err != nil {
					t.Fatalf("age runtime: %v", err)
				}
				failed, err := f.q.FailStaleTasks(ctx, db.FailStaleTasksParams{
					DispatchTimeoutSecs: timeoutSecs, RunningTimeoutSecs: timeoutSecs,
					RuntimeStaleSecs: staleSecs, RuntimeReconnectGraceSecs: graceSecs,
				})
				if err != nil {
					t.Fatalf("FailStaleTasks: %v", err)
				}
				for _, row := range failed {
					if row.ID == graphID {
						t.Fatal("FailStaleTasks failed a graph row")
					}
				}
				if _, err := f.q.ExpireStaleQueuedTasks(ctx, db.ExpireStaleQueuedTasksParams{ReconnectGraceSecs: graceSecs, MaxPerTick: maxPerTick}); err != nil {
					t.Fatalf("ExpireStaleQueuedTasks: %v", err)
				}
				offline, err := f.q.FailTasksForOfflineRuntimes(ctx, db.FailTasksForOfflineRuntimesParams{ReconnectGraceSecs: graceSecs, MaxPerTick: maxPerTick})
				if err != nil {
					t.Fatalf("FailTasksForOfflineRuntimes: %v", err)
				}
				for _, row := range offline {
					if row.ID == graphID {
						t.Fatal("FailTasksForOfflineRuntimes failed a graph row")
					}
				}
				if s := f.taskState(t, graphID); s.Status != "running" {
					t.Fatalf("sweeper family mutated graph status to %q", s.Status)
				}
				if s := f.taskState(t, legacyID); s.Status == "running" {
					t.Fatal("sweeper family left the matched legacy running row untouched")
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "failed" {
					t.Fatalf("legacy sweep status = %q, want failed", s.Status)
				}
			},
		},
		{
			name: "PromoteDueDeferredTasksForRuntime never clock-promotes graph readiness",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "deferred", testutil.Cols{"fire_at": time.Now().Add(-time.Hour)})
				legacyID := f.seedLegacyTask(t, "deferred", testutil.Cols{"fire_at": time.Now().Add(-time.Hour)})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				promoted, err := f.q.PromoteDueDeferredTasksForRuntime(ctx, db.PromoteDueDeferredTasksForRuntimeParams{
					RuntimeID: util.MustParseUUID(f.runtimeID), RuntimeStaleSecs: staleSecs,
				})
				if err != nil {
					t.Fatalf("PromoteDueDeferredTasksForRuntime: %v", err)
				}
				for _, row := range promoted {
					if row.ID == graphID {
						t.Fatal("deferred promote promoted a graph row")
					}
				}
				if s := f.taskState(t, graphID); s.Status != "deferred" {
					t.Fatalf("graph deferred promoted to %q", s.Status)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "queued" {
					t.Fatalf("legacy deferred promote status = %q, want queued", s.Status)
				}
			},
		},
		{
			name: "CreateRetryTask never clones a graph parent",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "failed", testutil.Cols{"completed_at": time.Now()})
				legacyID := f.seedLegacyTask(t, "failed", testutil.Cols{"completed_at": time.Now()})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				if _, err := f.q.CreateRetryTask(ctx, db.CreateRetryTaskParams{ID: graphID}); err == nil {
					t.Fatal("CreateRetryTask cloned a graph parent")
				}
				if _, err := f.q.CreateRetryTask(ctx, db.CreateRetryTaskParams{ID: legacyID}); err != nil {
					t.Fatalf("legacy retry: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				var retries int
				if err := f.pool.QueryRow(context.Background(), `SELECT count(*) FROM agent_task_queue WHERE parent_task_id = $1`, legacyID).Scan(&retries); err != nil {
					t.Fatalf("count legacy retries: %v", err)
				}
				if retries != 1 {
					t.Fatalf("legacy retry children = %d, want 1", retries)
				}
			},
		},
		{
			name: "DeleteUnstartedQuickCreateRetryTask keeps graph rows",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "queued")
				legacyID := f.seedLegacyTask(t, "queued")
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				n, err := f.q.DeleteUnstartedQuickCreateRetryTask(ctx, graphID)
				if err != nil || n != 0 {
					t.Fatalf("DeleteUnstartedQuickCreateRetryTask on graph row = %d, %v; want 0, nil", n, err)
				}
				if s := f.taskState(t, graphID); s.Status != "queued" {
					t.Fatalf("quick-create retry delete removed a graph row")
				}
				if n, err := f.q.DeleteUnstartedQuickCreateRetryTask(ctx, legacyID); err != nil || n != 1 {
					t.Fatalf("legacy quick-create retry delete = %d, %v", n, err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				var n int
				if err := f.pool.QueryRow(context.Background(), `SELECT count(*) FROM agent_task_queue WHERE id = $1`, legacyID).Scan(&n); err != nil {
					t.Fatalf("count legacy row: %v", err)
				}
				if n != 0 {
					t.Fatalf("legacy quick-create retry row still present")
				}
			},
		},
		{
			name: "LinkTaskToIssue never attaches an issue to a graph row",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "completed", testutil.Cols{"completed_at": time.Now()})
				legacyID := f.seedLegacyTask(t, "completed", testutil.Cols{"completed_at": time.Now()})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				issueID := f.dbfx.Issue(t, "graph fence issue", testutil.Cols{
					"workspace_id": f.workspaceID,
					"creator_type": "member",
					"creator_id":   f.userID,
					"priority":     "medium",
				})
				if err := f.q.LinkTaskToIssue(ctx, db.LinkTaskToIssueParams{ID: graphID, IssueID: util.MustParseUUID(issueID)}); err != nil {
					t.Fatalf("LinkTaskToIssue: %v", err)
				}
				if s := f.taskState(t, graphID); s.IssueID != nil {
					t.Fatalf("LinkTaskToIssue attached issue %s to a graph row", *s.IssueID)
				}
				if err := f.q.LinkTaskToIssue(ctx, db.LinkTaskToIssueParams{ID: legacyID, IssueID: util.MustParseUUID(issueID)}); err != nil {
					t.Fatalf("legacy issue link: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.IssueID == nil {
					t.Fatal("legacy quick-create row did not receive its issue link")
				}
			},
		},
		{
			name: "CancelAgentTasksByRuntimeOrAgent and ReassignTasksToRuntime exclude graph rows",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "queued")
				legacyID := f.seedLegacyTask(t, "queued")
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				cancelled, err := f.q.CancelAgentTasksByRuntimeOrAgent(ctx, db.CancelAgentTasksByRuntimeOrAgentParams{
					RuntimeIds: []pgtype.UUID{util.MustParseUUID(f.runtimeID)},
					AgentIds:   []pgtype.UUID{util.MustParseUUID(f.agentID)},
				})
				if err != nil {
					t.Fatalf("CancelAgentTasksByRuntimeOrAgent: %v", err)
				}
				for _, row := range cancelled {
					if row.ID == graphID {
						t.Fatal("revoke cancel reached a graph row")
					}
				}
				newRuntimeID := f.dbfx.Runtime(t, "graph-fence-runtime-2", testutil.Cols{
					"workspace_id": f.workspaceID,
					"status":       "online",
					"last_seen_at": time.Now(),
				})
				if _, err := f.q.ReassignTasksToRuntime(ctx, db.ReassignTasksToRuntimeParams{
					OldRuntimeID: util.MustParseUUID(f.runtimeID), NewRuntimeID: util.MustParseUUID(newRuntimeID),
				}); err != nil {
					t.Fatalf("ReassignTasksToRuntime: %v", err)
				}
				if s := f.taskState(t, graphID); s.RuntimeID == nil || *s.RuntimeID != f.runtimeID {
					t.Fatalf("ReassignTasksToRuntime moved a graph row to %v", s.RuntimeID)
				}
				// Restore the legacy row's runtime for later cases in this run.
				if _, err := f.pool.Exec(ctx, `UPDATE agent_task_queue SET runtime_id = $1 WHERE id = $2`, f.runtimeID, legacyID); err != nil {
					t.Fatalf("restore legacy runtime: %v", err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.Status != "cancelled" {
					t.Fatalf("legacy revoke-cancel status = %q, want cancelled", s.Status)
				}
			},
		},
		{
			name: "CancelSupersededDeferredRetriesForRuntimes leaves graph attempts to run revision control",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "deferred", testutil.Cols{"fire_at": time.Now().Add(-time.Hour)})
				legacyID := f.seedLegacyTask(t, "deferred", testutil.Cols{"fire_at": time.Now().Add(-time.Hour)})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				if _, err := f.q.CancelSupersededDeferredRetriesForRuntimes(ctx, []pgtype.UUID{util.MustParseUUID(f.runtimeID)}); err != nil {
					t.Fatalf("CancelSupersededDeferredRetriesForRuntimes: %v", err)
				}
				if s := f.taskState(t, graphID); s.Status != "deferred" {
					t.Fatalf("supersede-cancel changed graph status to %q", s.Status)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				// No successor exists for the legacy row, so it stays deferred: the
				// positive control is that the query ran and returned no error;
				// the supersede path is exercised by the dedicated handler suite.
				if s := f.taskState(t, legacyID); s.Status != "deferred" {
					t.Fatalf("legacy deferred-without-successor status = %q, want deferred (no false supersede)", s.Status)
				}
			},
		},
		{
			name: "UnbindTasksFromRuntime keeps graph runtime binding",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				graphID := f.seedGraphTask(t, "completed", testutil.Cols{"completed_at": time.Now()})
				legacyID := f.seedLegacyTask(t, "completed", testutil.Cols{"completed_at": time.Now()})
				return graphID, legacyID
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				if _, err := f.q.UnbindTasksFromRuntime(ctx, util.MustParseUUID(f.runtimeID)); err != nil {
					t.Fatalf("UnbindTasksFromRuntime: %v", err)
				}
				if s := f.taskState(t, graphID); s.RuntimeID == nil || *s.RuntimeID != f.runtimeID {
					t.Fatal("UnbindTasksFromRuntime unbound a graph row")
				}
				if s := f.taskState(t, legacyID); s.RuntimeID != nil {
					t.Fatal("legacy terminal row was not unbound")
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if s := f.taskState(t, legacyID); s.RuntimeID != nil {
					t.Fatalf("legacy terminal runtime = %v, want unbound", *s.RuntimeID)
				}
			},
		},
		{
			name: "Legacy claim candidate listing excludes graph rows",
			setup: func(t *testing.T, f *graphFenceFixture) (pgtype.UUID, pgtype.UUID) {
				return f.seedGraphTask(t, "queued"), f.seedLegacyTask(t, "queued")
			},
			run: func(t *testing.T, f *graphFenceFixture, graphID, legacyID pgtype.UUID) {
				runtimes := []pgtype.UUID{util.MustParseUUID(f.runtimeID)}
				candidates, err := f.q.ListQueuedClaimCandidatesByRuntimes(ctx, runtimes)
				if err != nil || len(candidates) != 1 || candidates[0].ID != legacyID {
					t.Fatalf("batch candidates must contain only the legacy row: count=%d err=%v", len(candidates), err)
				}
				single, err := f.q.ListQueuedClaimCandidatesByRuntime(ctx, runtimes[0])
				if err != nil || len(single) != 1 || single[0].ID != legacyID {
					t.Fatalf("singular candidates must contain only the legacy row: count=%d err=%v", len(single), err)
				}
			},
			legacyAssert: func(t *testing.T, f *graphFenceFixture, legacyID pgtype.UUID) {
				if f.taskState(t, legacyID).Status != "queued" {
					t.Fatal("candidate listing changed the legacy queued row")
				}
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			f := newGraphFenceFixture(t)
			graphID, legacyID := tc.setup(t, f)
			before := f.taskJSON(t, graphID)
			tc.run(t, f, graphID, legacyID)
			if after := f.taskJSON(t, graphID); after != before {
				t.Fatalf("graph row mutated:\nbefore %s\nafter  %s", before, after)
			}
			if tc.legacyAssert == nil {
				t.Fatal("missing legacyAssert positive control")
			}
			tc.legacyAssert(t, f, legacyID)
		})
	}
}

func TestGraphDeferredPollingIgnoresGraphRows(t *testing.T) {
	f := newGraphFenceFixture(t)
	ctx := context.Background()
	graphID := f.seedGraphTask(t, "deferred", testutil.Cols{"fire_at": time.Now().Add(-time.Hour)})
	legacyDeadline := time.Now().Add(time.Hour).UTC().Truncate(time.Microsecond)
	legacyID := f.seedLegacyTask(t, "deferred", testutil.Cols{"fire_at": legacyDeadline})
	before := f.taskJSON(t, graphID)
	params := db.NextDeferredTaskFireAtForRuntimesParams{RuntimeIds: []pgtype.UUID{util.MustParseUUID(f.runtimeID)}, RuntimeStaleSecs: 3600}
	next, err := f.q.NextDeferredTaskFireAtForRuntimes(ctx, params)
	if err != nil || !next.Valid || !next.Time.Equal(legacyDeadline) {
		t.Fatalf("next deferred deadline must match the legacy row: got=%v err=%v", next, err)
	}
	if _, err := f.pool.Exec(ctx, `DELETE FROM agent_task_queue WHERE id = $1`, legacyID); err != nil {
		t.Fatal(err)
	}
	next, err = f.q.NextDeferredTaskFireAtForRuntimes(ctx, params)
	if err != nil || next.Valid {
		t.Fatalf("graph-only deferred queue must have no legacy deadline: got=%v err=%v", next, err)
	}
	if f.taskJSON(t, graphID) != before {
		t.Fatal("deferred polling changed the graph row")
	}
}

// TestCountRunningTasksIncludesUncertainGraphReservation pins the one counting
// query that must INCLUDE graph rows: an execution_uncertain graph reservation
// may still hold a live process, so a legacy claim must not consume its slot.
func TestCountRunningTasksIncludesUncertainGraphReservation(t *testing.T) {
	f := newGraphFenceFixture(t)
	ctx := context.Background()
	f.seedGraphTask(t, "failed", testutil.Cols{"completed_at": time.Now(), "execution_uncertain": true})
	count, err := f.q.CountRunningTasks(ctx, util.MustParseUUID(f.agentID))
	if err != nil {
		t.Fatalf("CountRunningTasks: %v", err)
	}
	if count != 1 {
		t.Fatalf("CountRunningTasks = %d, want 1 (uncertain graph reservation counts)", count)
	}
	// The same graph row with certainty cleared stops reserving the slot.
	if _, err := f.pool.Exec(ctx, `UPDATE agent_task_queue SET execution_uncertain = FALSE, status = 'failed' WHERE agent_id = $1`, f.agentID); err != nil {
		t.Fatalf("clear uncertain flag: %v", err)
	}
	count, err = f.q.CountRunningTasks(ctx, util.MustParseUUID(f.agentID))
	if err != nil {
		t.Fatalf("CountRunningTasks after clear: %v", err)
	}
	if count != 0 {
		t.Fatalf("CountRunningTasks after clear = %d, want 0", count)
	}
}
